"""phase2_scan_findings_tables

Revision ID: 878b48b2cd5f
Revises: 
Create Date: 2026-07-22 21:43:19.463961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '878b48b2cd5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_files_found', sa.Integer(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('source_hash_before', sa.String(length=64), nullable=True),
    sa.Column('source_hash_after', sa.String(length=64), nullable=True),
    sa.Column('integrity_verified', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('detected_type', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('sensitivity_hint', sa.Boolean(), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('skipped_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_inventory_scan_id'), 'file_inventory', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('scanner_id', sa.String(length=64), nullable=False),
    sa.Column('scanner_version', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('finding_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('banking_domains', sa.JSON(), nullable=False),
    sa.Column('source_relative_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('masked_evidence', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('remediation_mode', sa.String(length=20), nullable=False),
    sa.Column('read_only_confirmation', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_table('scanner_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('scanner_id', sa.String(length=64), nullable=False),
    sa.Column('scanner_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=False),
    sa.Column('files_errored', sa.Integer(), nullable=False),
    sa.Column('findings_produced', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_executions_scan_id'), 'scanner_executions', ['scan_id'], unique=False)
    op.create_table('domain_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('file_inventory_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_inventory_id'], ['file_inventory.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_mappings_file_inventory_id'), 'domain_mappings', ['file_inventory_id'], unique=False)
    op.create_index(op.f('ix_domain_mappings_scan_id'), 'domain_mappings', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_mappings_scan_id'), table_name='domain_mappings')
    op.drop_index(op.f('ix_domain_mappings_file_inventory_id'), table_name='domain_mappings')
    op.drop_table('domain_mappings')
    op.drop_index(op.f('ix_scanner_executions_scan_id'), table_name='scanner_executions')
    op.drop_table('scanner_executions')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_file_inventory_scan_id'), table_name='file_inventory')
    op.drop_table('file_inventory')
    op.drop_table('scans')
    # ### end Alembic commands ###
