"""phase3_controls_evidence_scoring

Revision ID: c05c9974fade
Revises: 878b48b2cd5f
Create Date: 2026-07-22 22:30:24.935856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c05c9974fade'
down_revision: Union[str, None] = '878b48b2cd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('subdomain', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('applies_to_domains', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_id'), 'controls', ['control_id'], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('evidence_completeness', sa.String(length=16), nullable=False),
    sa.Column('decision_category', sa.String(length=32), nullable=False),
    sa.Column('files_evaluated', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('override_of', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['override_of'], ['scores.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_scan_id'), 'scores', ['scan_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('retrieved_via', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_control_id'), 'evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_control_id'), 'recommendations', ['control_id'], unique=False)
    op.create_index(op.f('ix_recommendations_finding_id'), 'recommendations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_recommendations_scan_id'), 'recommendations', ['scan_id'], unique=False)
    op.add_column('findings', sa.Column('human_review_status', sa.String(length=16), nullable=False))
    op.add_column('findings', sa.Column('reviewed_by', sa.String(length=128), nullable=True))
    op.add_column('findings', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'reviewed_at')
    op.drop_column('findings', 'reviewed_by')
    op.drop_column('findings', 'human_review_status')
    op.drop_index(op.f('ix_recommendations_scan_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_finding_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_control_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_control_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_scores_scan_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_controls_control_id'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
