"""phase4_audit_trail_control_evaluations

Revision ID: a14a5514b9ab
Revises: c05c9974fade
Create Date: 2026-07-23 18:30:16.283584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a14a5514b9ab'
down_revision: Union[str, None] = 'c05c9974fade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_scan_id'), 'audit_events', ['scan_id'], unique=False)
    op.create_table('control_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_evaluations_control_id'), 'control_evaluations', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_evaluations_scan_id'), 'control_evaluations', ['scan_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE (hand-edited, not autogenerated): autogenerate also detected a
    # `DROP TABLE vs_phase2_roundtrip_test` here. That table is not one of
    # this platform's SQLAlchemy models — it is a pgvector collection table
    # created directly by rag/vectorstores/pgvector_store.py's own
    # ensure_schema()/add() calls during an earlier live-integration test
    # run (tests/integration/test_postgres_persistence.py), entirely
    # outside Alembic's management. Autogenerate diffs the live database
    # against Base.metadata and has no way to know that distinction, so it
    # proposed dropping a table this migration has no business touching.
    # Removed by hand; see docs/vector_backend_decision.md for how
    # pgvector collection tables are actually managed.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_evaluations_scan_id'), table_name='control_evaluations')
    op.drop_index(op.f('ix_control_evaluations_control_id'), table_name='control_evaluations')
    op.drop_table('control_evaluations')
    op.drop_index(op.f('ix_audit_events_scan_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
