from __future__ import annotations

import os

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

import storage.db.models  # noqa: F401 — registers tables with Base.metadata
from core.config import Settings
from scanners.scan_orchestrator import run_scan
from scanners.source_ingestion import ingest_local_directory
from storage.db.models.finding import Finding
from storage.db.models.scan import Scan
from storage.db.repositories import ScanRepository

# Live PostgreSQL/pgvector integration test
# (BANKING_PLATFORM_INTEGRATION_PLAN.md Phase 2 brief §9: "If Docker is
# available and using the existing Docker Compose setup is safe, you may
# start the local PostgreSQL/pgvector service and run real integration
# tests"). This test module is SKIPPED — not silently passed — when
# DATABASE_URL is not set, so its status is always explicit either way.
#
# In this Phase 2 implementation session: Docker was available, the
# `db` service from deployment/docker-compose.yml was started with a
# local-only, non-default test credential (never committed anywhere), the
# alembic migration in alembic/versions/0001_phase2_scan_findings_tables.py
# was generated by autogenerate against this same schema and applied with
# `alembic upgrade head`, and this test module was run against that live
# instance. See PHASE_2_COMPLETION_REPORT.md for the actual recorded
# result of that run — do not take this module's mere presence as proof
# it was executed; check the completion report for the verified outcome.

DATABASE_URL = os.environ.get("DATABASE_URL")

pytestmark = pytest.mark.skipif(
    not DATABASE_URL,
    reason="DATABASE_URL not set — no live PostgreSQL/pgvector server available in this run",
)


@pytest.fixture()
def engine():
    eng = create_engine(DATABASE_URL, pool_pre_ping=True)
    yield eng
    eng.dispose()


def _settings(tmp_path) -> Settings:
    return Settings(
        _env_file=None,
        allowed_scan_paths=[str(tmp_path)],
        scan_temp_dir=str(tmp_path / "scan_tmp"),
        database_url=DATABASE_URL,
    )


def test_can_connect_and_pgvector_extension_is_available(engine):
    with engine.connect() as conn:
        row = conn.execute(text("SELECT 1")).scalar()
        assert row == 1
        ext = conn.execute(
            text("SELECT extname FROM pg_extension WHERE extname = 'vector'")
        ).fetchone()
        assert ext is not None, "pgvector extension is not installed on this database"


def test_alembic_tables_exist(engine):
    with engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' ORDER BY table_name"
            )
        ).fetchall()
    table_names = {r[0] for r in rows}
    assert {"scans", "file_inventory", "domain_mappings", "findings", "scanner_executions"} <= table_names


def test_full_scan_persists_to_live_postgres(tmp_path, engine):
    project = tmp_path / "project"
    project.mkdir()
    (project / "app.py").write_text('PASSWORD = "hunter2value123"\n')
    settings = _settings(tmp_path)

    handle = ingest_local_directory(str(project), settings)
    try:
        result = run_scan(handle, settings)
    finally:
        handle.cleanup()

    with Session(engine) as session:
        repo = ScanRepository(session)
        repo.save(result)

    with Session(engine) as verify_session:
        scan_row = verify_session.get(Scan, result.summary.scan_id)
        assert scan_row is not None
        assert scan_row.integrity_verified is True

        findings = (
            verify_session.query(Finding).filter(Finding.scan_id == result.summary.scan_id).all()
        )
        assert len(findings) >= 1
        for row in findings:
            assert "hunter2value123" not in row.masked_evidence


def test_pgvector_store_health_check_against_live_server(tmp_path):
    from rag.vectorstores.pgvector_store import PgVectorStore

    store = PgVectorStore(database_url=DATABASE_URL, collection_name="phase2_health_check")
    status = store.health_check()
    assert status.healthy is True
    assert status.backend == "pgvector"


def test_pgvector_store_add_and_search_roundtrip_against_live_server(tmp_path):
    from core.contracts import Chunk
    from rag.vectorstores.pgvector_store import PgVectorStore

    store = PgVectorStore(
        database_url=DATABASE_URL, collection_name="phase2_roundtrip_test", dimension=8
    )
    store.ensure_schema()
    store.clear()

    vector = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
    store.add(
        [
            Chunk(
                chunk_id="c1",
                doc_id="doc1",
                text="sample banking policy text",
                embedding=vector,
                metadata={"doc_id": "doc1"},
            )
        ]
    )
    results = store.search(vector, top_k=1)
    assert len(results) == 1
    assert results[0].chunk_id == "c1"
    store.clear()
